#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_INPUT_SPARCSPKR)		+= sparcspkr.o
obj-$(CONFIG_INPUT_PCSPKR)		+= pcspkr.o
obj-$(CONFIG_INPUT_M68K_BEEP)		+= m68kspkr.o
obj-$(CONFIG_INPUT_UINPUT)		+= uinput.o
obj-$(CONFIG_INPUT_WISTRON_BTNS)	+= wistron_btns.o
obj-$(CONFIG_HP_SDC_RTC)		+= hp_sdc_rtc.o
obj-$(CONFIG_INPUT_IXP4XX_BEEPER)	+= ixp4xx-beeper.o
obj-$(CONFIG_W55FA93_KEYPAD_1X4_I)	+= w55fa93_keypad_1x4_input.o
obj-$(CONFIG_W55FA93_KEYPAD_3X3_I)	+= w55fa93_keypad_3x3_input.o
obj-$(CONFIG_W55FA93_KEYPAD_MxN)	+= w55fa93_keypad_mxn_input.o
obj-$(CONFIG_W55FA93_8_BUTTONS)		+= w55fa93_keypad_8buttons.o
