obj-$(CONFIG_W55FA93_VIDEOIN)    += DrvVideoIn.o
obj-$(CONFIG_W55FA93_VIDEOIN)    += DrvFsc.o
obj-$(CONFIG_W55FA93_VIDEOIN)    += DrvI2C.o
obj-$(CONFIG_W55FA93_VIDEOIN)    += videoin.o
obj-$(CONFIG_W55FA93_VIDEOIN)    += sensor.o
obj-$(CONFIG_W55FA93_VIDEOIN)    += vin_ioctl.o

